import type { Metadata } from "next";
import "./globals.css";
import { HeaderMain } from "./components/header_main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="pt-br"
    >
      <body
        className="
          bg-black select-none
        "
      >
        <HeaderMain />
        
        <div
          className="
            z-0 mt-12
          "
        >
          {children}
        </div>
        
      </body>
    </html>
  );
}
